version: 0.2

env:
  variables:
     S3BUCKET: "value"
phases:
  install:
    commands:
      - pip install boto3
      - pip install awscli
  build:
    commands:
      - echo Archiving Source Code
      - zip lambdacode.zip lambda.go
      - aws s3 cp lambdacode.zip $S3BUCKET
  post_build:
    commands:
      - echo Build completed on `date`
  artifacts:
    - lambdacode.zip
    - ConfigRuleParamters.json