AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  CodeBucket:
    Type: String
    Default: "us-east-1-jp-cfn-241-lambda-code"
Resources:
  LambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "lambda-config-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Principal:
            Service:
              - "lambda.amazonaws.com"
          Action:
            - "sts:AssumeRole"
      Policies:
        -
          PolicyName: "lambda-config-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - 
                Effect: "Allow"
                Action: "*"
                Resource:
                  - "*"
  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties: 
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: "lambdacode.zip"
        # S3ObjectVersion: !Ref ObjectVersion
      Description: Checks if S3 bucket names comply with naming convention
      FunctionName: main
      Handler: Handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/${LambdaRole} 
      Runtime: go1.x

  ConfigPermission:
    Type: "AWS::Lambda::Permission"
    DependsOn: LambdaFunction
    Properties:
      FunctionName: arn:aws:lambda:us-east-1:324320755747:function:S3BucketComplianceCheck
      Action: "lambda:InvokeFunction"
      Principal: "config.amazonaws.com"

  ConfigRule:
    Type: "AWS::Config::ConfigRule"
    DependsOn: ConfigPermission
    Properties:
      Description: Evaluates if S3 Bucket Names start with AWS Region
      MaximumExecutionFrequency: "Six_Hours"
      Scope:
        ComplianceResourceTypes:
          -
            AWS::S3::Bucket
      Source:
        Owner: CUSTOM_LAMBDA
        SourceDetails:
          - 
            EventSource: "aws.config"
            MessageType: "ConfigurationItemChangeNotification"
        SourceIdentifier: arn:aws:lambda:us-east-1:324320755747:function:S3BucketComplianceCheck