---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Setup Config Service"
Parameters:
  DesiredRegion:
    Description: The Desired Deployment Region
    Default: us-east-1
    Type: String
    AllowedValues:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-south-1
      - ap-southeast-1
      - ap-southeast-2
      - ca-central-1
      - cn-northwest-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - sa-east-1

  
Conditions: 
  RegionDefault: !Equals [ !Ref "AWS::Region" , !Ref DesiredRegion ]

Resources:
  ConfigBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: BucketOwnerFullControl
  
  ConfigBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ConfigBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AWSConfigBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action: s3:GetBucketAcl
            Resource:
              - !Sub arn:aws:s3:::${ConfigBucket}
          - Sid: AWSConfigBucketDelivery
            Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action: s3:PutObject
            Resource:
              - !Sub arn:aws:s3:::${ConfigBucket}/AWSLogs/${AWS::AccountId}/*

  ConfigRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - 
            Effect: "Allow"
            Principal:
              Service: "config.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "StelligentLabsConfigPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -  
                Effect: "Allow"
                Action: "s3:PutObject"
                Resource: 
                  - !Sub arn:aws:s3:::${ConfigBucket}/AWSLogs/${AWS::AccountId}/*
                Condition: 
                  StringLike: 
                    s3:x-amz-acl: "bucket-owner-full-control"
              -  
                Effect: "Allow"
                Action: "s3:GetBucketAcl"
                Resource: !Sub "arn:aws:s3:::${ConfigBucket}"
              -  
                Effect: "Allow"
                Action: 
                  - "config:Put*"
                  - "ec2:Describe*"
                  - "iam:List*"
                  - "iam:Get*"
                Resource: "*"
              -  
                Effect: Allow
                Action: "s3:PutObject"
                Resource: !Sub "${ConfigBucket}/AWSLogs/${AWS::AccountId}/*"
                Condition:
                  StringLike:
                    - s3:x-amz-acl: "bucket-owner-full-control"
              -
                Effect: Allow
                Action: 
                  - s3:GetBucketAcl
                Resource: !Sub "arn:aws:s3:::${ConfigBucket}"
              - 
                Effect: Allow
                Action:
                  - "config:Put*"
                  - "iam:List*"
                  - "iam:Get*"
                Resource: "*"
              
# Delivery Channel
  DeliveryChannel:
    Type: "AWS::Config::DeliveryChannel"
    Properties:
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: Twelve_Hours
      S3BucketName: !Ref ConfigBucket
           
#Config Recorder 
  ConfigRecorder:
    Type: "AWS::Config::ConfigurationRecorder"
    Properties:
      Name: StelligentLabsConfigRecorder
      RecordingGroup:
        AllSupported: True
        IncludeGlobalResourceTypes: !If [RegionDefault, True, False]
      RoleARN: !GetAtt ConfigRole.Arn