---
Description: Automate the creation of a custom AWS Config Rule that 
  evaluates S3 buckets as compliant only when the bucket name starts with the region it's in
  (i.e. 'us-west-2-awesomebucket')
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EmailAddress:
    Description: Email Address for sending SNS notifications for CodeCommit
    Type: String
  RepositoryBranch:
    Description: The name of the branch for the CodeCommit repo
    Type: String
    Default: master
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Can contain only ASCII characters.

Resources:
  ArtifactBucket:
    Properties:
      BucketName: "us-east-1-jp-cfn-241-lambda-code"
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete

  CompliantBucket:
    Properties:
      BucketName: "us-east-1-jp-cfn-241-test-1"
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete

  NonCompliantBucket:
    Properties:
      BucketName: "no-region-jp-cfn-241-test-2"
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - codebuild.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: jp-cfn-241-codebuild-service
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action: "*"
              Resource: "*"
            
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codepipeline.amazonaws.com
            - lambda.amazonaws.com
            - config.amazonaws.com
            - cloudformation.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: codepipeline-service
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Action: 
                - "*"
              Effect: Allow
              Resource:
                - "*"
          # - 
          #   Action:
          #   - codecommit:GetBranch
          #   - codecommit:GetCommit
          #   - codecommit:UploadArchive
          #   - codecommit:GetUploadArchiveStatus
          #   - codecommit:CancelUploadArchive
          #   - codebuild:*
          #   Resource:
          #     - "*"
          #   Effect: Allow
          # - Action:
          #   - s3:*
          #   Resource: 
          #     - "*"
          #   Effect: Allow
          # - Action:
          #   - s3:PutObject
          #   Resource:
          #     - arn:aws:s3:::codepipeline*
          #   Effect: Allow
          # - Action:
          #   - lambda:InvokeFunction
          #   - lambda:ListFunctions
          #   Resource: 
          #     - "*"
          #   Effect: Allow
          # - Action:
          #   - cloudformation:*
          #   Effect: Allow
          #   Resource: "*"
          Version: '2012-10-17'

  CodeBuild:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: jp-cfn-241
      Environment:
        EnvironmentVariables:
          - Name: S3BUCKET
            Type: PLAINTEXT
            Value: !Sub s3://${ArtifactBucket}
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/golang:1.10
      Source:
        Location: "arn:aws:codecommit:us-east-1:324320755747:JP-CFN-241"
        Type: CODECOMMIT
      TimeoutInMinutes: 10
      ServiceRole: !GetAtt 
        - CodeBuildRole
        - Arn
      Artifacts:
        Type: S3
        Location: !Ref ArtifactBucket

  ConfigRulePipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      RoleArn: !GetAtt
        - CodePipelineRole
        - Arn
      Stages:
        - 
          Name: Source
          Actions:
            - InputArtifacts: []
              Name: CodeCommit
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: '1'
                Provider: CodeCommit
              OutputArtifacts:
                - Name: Source
              Configuration:
                BranchName: !Ref RepositoryBranch
                RepositoryName: JP-CFN-241
              RunOrder: 1
        - 
          Name: BuildLambda
          Actions:
            - InputArtifacts:
              - Name: Source
              Name: BuildLambda
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuild
              RunOrder: 2
        - 
          Name: CreateConfigRule
          Actions: 
            - 
              InputArtifacts:
                - Name: Source
              Name: CreateConfigRule
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              
              Configuration:
                StackName: jp-cfn-241-config-rule
                RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/${CodePipelineRole}
                ActionMode: CREATE_UPDATE
                TemplatePath: Source::ConfigRule.yaml
                # TemplateConfiguration: Source::ConfigRuleParamters.json
              RunOrder: 3

        
    


